### ISSUE TITLE
yte error: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by tinyheero** [yte-template-engine/yte#31]
I am running into this issue when trying to create a YAML file from the following YAML template using yte (v1.5.1):

```yaml
__use_yte__: true
name: "YTE Bug"
navbar:
  title: "YTE Bug"
  left:
    - text: "Per-patient Reports"
      menu: ?per_patient_reports
    - text: "Pan-patient Reports"
      menu:
        - text: "Test 1"
          href: "01.html"
        - text: "Test 2"
          href: "02.html"
```

Running the running Python code:

```python
from yte import process_yaml

variables = {
    "per_patient_reports": [{"text": "Disease A", "href": "diseaseA.html"}]
}

with open("_site_template.yaml", "r") as template, open(
    "_site.yml", "w"
) as outfile:
    result = process_yaml(
        template, variables=variables, outfile=outfile, require_use_yte=True
    )
```

Results in the following error message:

```python
...
File /usr/local/lib/python3.9/site-packages/yte/process.py:125, in _process_dict_items(yaml_value, variables, context, disable_features)
    120         key_context.rendered.append(key_result)
    122         value_result = _process_yaml_value(
    123             value, variables, key_context, disable_features
    124         )
--> 125         variables["doc"]._insert(key_context, value_result)
    127         yield {key_result: value_result}
    128 yield from conditional.process_conditional(variables, key_context, disable_features)

File /usr/local/lib/python3.9/site-packages/yte/document.py:69, in Document._insert(self, context, value)
     66         inner[key] = Subdocument()
     67     inner = inner[key]
---> 69 inner[context.rendered[-1]] = value

TypeError: list indices must be integers or slices, not str
```

Oddly enough, if you swap the order of the YAML keys:

```yaml
__use_yte__: true
name: "YTE Works"
navbar:
  title: "YTE Work"
  left:
    - text: "Pan-patient Reports"
      menu:
        - text: "Test 1"
          href: "01.html"
        - text: "Test 2"
          href: "02.html"
    - text: "Per-patient Reports"
      menu: ?per_patient_reports
```

This works producing the following `_site.yml` file:

```yaml
name: YTE Works
navbar:
  title: YTE Work
  left:
  - text: Pan-patient Reports
    menu:
    - text: Test 1
      href: 01.html
    - text: Test 2
      href: 02.html
  - text: Per-patient Reports
    menu:
    - text: Disease A
      href: diseaseA.html
```
