### ISSUE TITLE
Confuses list of objects in the yaml with similar structures

### ISSUE THREAD

**Issue by starptr** [yte-template-engine/yte#42]
YTE deletes keys when I don't expect them to be deleted. For example, the following input yaml file:
```yaml
---
? ''
: - octodns:
      cloudflare:
        auto-ttl: true
        proxied: true
        ignored: true
    ttl: 300
    type: AAAA
    value: '100::'
  - octodns:
      cloudflare:
        auto-ttl: true
    ttl: 300
    type: MX
    values:
    - exchange: eforward1.registrar-servers.com.
      preference: 10
    - exchange: eforward2.registrar-servers.com.
      preference: 10
    - exchange: eforward3.registrar-servers.com.
      preference: 10
    - exchange: eforward4.registrar-servers.com.
      preference: 15
    - exchange: eforward5.registrar-servers.com.
      preference: 20
  - octodns:
      cloudflare:
        auto-ttl: true
    ttl: 300
    type: TXT
    value: v=spf1 include:spf.efwd.registrar-servers.com ~all
mc:
  octodns:
    cloudflare:
      auto-ttl: true
  ttl: 300
  type: A
  value: 152.67.224.194
```
results in the following output yaml file:
```yaml
? ''
: - octodns:
      cloudflare: ######### The `proxied` and `ignored` keys are gone!
        auto-ttl: true
    ttl: 300
    type: AAAA
    value: '100::'
  - octodns:
      cloudflare: &id001
        auto-ttl: true
    ttl: 300
    type: MX
    values:
    - exchange: eforward1.registrar-servers.com.
      preference: 10
    - exchange: eforward2.registrar-servers.com.
      preference: 10
    - exchange: eforward3.registrar-servers.com.
      preference: 10
    - exchange: eforward4.registrar-servers.com.
      preference: 15
    - exchange: eforward5.registrar-servers.com.
      preference: 20
  - octodns:
      cloudflare: *id001
    ttl: 300
    type: TXT
    value: v=spf1 include:spf.efwd.registrar-servers.com ~all
mc:
  octodns:
    cloudflare:
      auto-ttl: true
  ttl: 300
  type: A
  value: 152.67.224.194
```
